version: '3.9'

services:
  db:
    image: postgres
    container_name: worldproxy_database
    environment:
      - POSTGRES_DB=worldproxy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build: ./server
    container_name: worldproxy_server
    command: bash -c "python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=(9#(q@qq!t+azn)4!&8)k93f5ji@9z%vs&_qn_ys(insecure)
      - DATABASE_URL=postgres://postgres:root@db/worldproxy
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  client:
    build: 
      context: ./client
      target: 'develop-stage'
    container_name: worldproxy_client
    ports: 
      - "5173:5173"
    environment:
      - VITE_COUNTRIES_BORDERS_GEOJSON=https://datahub.io/core/geo-countries/r/0.geojson
      - VITE_SERVER_ADDRESS=http://localhost:8000
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    command: /bin/sh -c "npm run dev"
    depends_on:
      - server
