version: '3.8'

services:
  db:
    image: postgres
    container_name: worldproxy_database
    environment:
      - POSTGRES_DB=worldproxy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  server:
    build: ./server
    container_name: worldproxy_server
    command: python /code/manage.py makemigrations && python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - server/world_server/.env
    depends_on:
      db:
        condition: service_started
  client:
    build: 
      context: ./client
    container_name: worldproxy_client
    ports: 
      - "4200:4200"
    depends_on:
      - server
