# Generated by Django 3.2.18 on 2023-04-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
