# Generated by Django 3.2.18 on 2023-04-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_proxy', '0002_alter_country_population'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
