# Generated by Django 3.2.18 on 2023-04-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='translations',
            field=models.JSONField(null=True),
        ),
    ]
