# Generated by Django 3.2.18 on 2023-10-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='iso_code',
            new_name='iso3',
        ),
    ]
