# Generated by Django 3.2.18 on 2023-11-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryEconomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=3)),
                ('gdp_real', models.BigIntegerField(help_text='purchasing power parity in billion dollars', null=True)),
                ('gdp_gross', models.BigIntegerField(help_text='in billion dollars', null=True)),
                ('gdp_agriculture', models.DecimalField(decimal_places=2, help_text='percentage of total GDP', max_digits=2, null=True)),
                ('gdp_industry', models.DecimalField(decimal_places=2, help_text='percentage of total GDP', max_digits=2, null=True)),
                ('gdp_services', models.DecimalField(decimal_places=2, help_text='percentage of total GDP', max_digits=2, null=True)),
                ('real_gdp_growth_rate', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('real_gdp_per_capita', models.BigIntegerField(help_text='in dollars', null=True)),
                ('inflation_rate', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
                ('industrial_production_growth_rate', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
                ('labor_force', models.BigIntegerField(null=True)),
                ('labor_force_agriculture', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
                ('labor_force_industry', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
                ('labor_force_services', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
                ('unemployment_rate', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
                ('unemployment_rate_youth', models.DecimalField(decimal_places=2, help_text='percentage of unemployment 15-24', max_digits=2, null=True)),
                ('population_below_poverty_line', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
                ('public_debt', models.DecimalField(decimal_places=2, help_text='percentage of GDP', max_digits=2, null=True)),
                ('taxes', models.DecimalField(decimal_places=2, help_text='percentage of GDP', max_digits=2, null=True)),
                ('exports', models.BigIntegerField(help_text='in billion dollars', null=True)),
                ('imports', models.BigIntegerField(help_text='in billion dollars', null=True)),
            ],
            options={
                'db_table': 'country_economy',
            },
        ),
        migrations.CreateModel(
            name='CountrySociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=3)),
                ('languages', models.JSONField(null=True)),
                ('population', models.BigIntegerField(null=True)),
                ('population_growth_rate', models.BigIntegerField(null=True)),
                ('population_0_14_rate', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('population_15_64_rate', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('population_65_more_rate', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('population_males_0_14', models.BigIntegerField(null=True)),
                ('population_females_0_14', models.BigIntegerField(null=True)),
                ('population_males_15_64', models.BigIntegerField(null=True)),
                ('population_females_15_64', models.BigIntegerField(null=True)),
                ('population_males_65_more', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('population_females_65_more', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('median_age', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('median_age_male', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('median_age_female', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('birth_rate', models.DecimalField(decimal_places=2, help_text='births every 1000 population', max_digits=2, null=True)),
                ('death_rate', models.DecimalField(decimal_places=2, help_text='deaths every 1000 population', max_digits=2, null=True)),
                ('net_migration_rate', models.DecimalField(decimal_places=2, help_text='migrants every 1000 population', max_digits=2, null=True)),
                ('urban_population_rate', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('life_expectancy_at_birth', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('life_expectancy_at_birth_male', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('life_expectancy_at_birth_female', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('fertility_rate', models.DecimalField(decimal_places=2, help_text='children born/woman', max_digits=2, null=True)),
                ('health_expenditure', models.DecimalField(decimal_places=2, help_text='as a percentage of GDP', max_digits=2, null=True)),
                ('physicians_density', models.DecimalField(decimal_places=2, help_text='physicians every 1000 population', max_digits=2, null=True)),
                ('hospital_bed_density', models.DecimalField(decimal_places=2, help_text='beds every 1000 population', max_digits=2, null=True)),
                ('obesity_rate', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('alcohol_consumption_per_capita', models.DecimalField(decimal_places=2, help_text='liters', max_digits=2, null=True)),
                ('beer_consumption_per_capita', models.DecimalField(decimal_places=2, help_text='liters', max_digits=2, null=True)),
                ('wine_consumption_per_capita', models.DecimalField(decimal_places=2, help_text='liters', max_digits=2, null=True)),
                ('spirits_consumption_per_capita', models.DecimalField(decimal_places=2, help_text='liters', max_digits=2, null=True)),
                ('tobacco_use', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
                ('tobacco_use_male', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
                ('tobacco_use_female', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
                ('married_women_rate', models.DecimalField(decimal_places=2, help_text='ages 15-49', max_digits=2, null=True)),
                ('literacy_rate', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
                ('literacy_rate_male', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
                ('literacy_rate_female', models.DecimalField(decimal_places=2, help_text='percentage', max_digits=2, null=True)),
            ],
            options={
                'db_table': 'country_society',
            },
        ),
        migrations.RemoveField(
            model_name='country',
            name='borders',
        ),
        migrations.RemoveField(
            model_name='country',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
    ]
