# Generated by Django 3.2.18 on 2023-10-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrygeography',
            old_name='coordinates',
            new_name='lat_lng',
        ),
    ]
