# Generated by Django 3.2.18 on 2023-10-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_rename_coordinates_countrygeography_lat_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrygeography',
            name='lat_lng',
            field=models.JSONField(null=True),
        ),
    ]
