# Generated by Django 3.2.18 on 2023-04-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_country_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currencies',
            field=models.JSONField(null=True),
        ),
    ]
