# Generated by Django 3.2.18 on 2023-10-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_rename_iso_code_country_iso3'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='Country',
        ),
    ]
