# Generated by Django 3.2.18 on 2023-10-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_country_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
