# Generated by Django 3.2.18 on 2023-04-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_country_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='map',
            field=models.URLField(null=True),
        ),
    ]
