# Generated by Django 3.2.18 on 2023-11-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_countrysociety_population_growth_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrysociety',
            name='population_growth_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
