# Generated by Django 3.2.18 on 2023-04-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_country_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.JSONField(null=True),
        ),
    ]
