# Generated by Django 3.2.18 on 2023-10-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_alter_country_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
