# Generated by Django 3.2.18 on 2023-04-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_country_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='borders',
            field=models.JSONField(null=True),
        ),
    ]
