# Generated by Django 3.2.18 on 2023-11-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_auto_20231101_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrysociety',
            old_name='birth_rate',
            new_name='birth_every_1000',
        ),
        migrations.RenameField(
            model_name='countrysociety',
            old_name='death_rate',
            new_name='death_every_1000',
        ),
    ]
