# Generated by Django 3.2.18 on 2023-10-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_countrycodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(),
        ),
    ]
