# Generated by Django 3.2.18 on 2023-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_country_borders'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='income_level',
            field=models.JSONField(null=True),
        ),
    ]
