# Generated by Django 3.2.18 on 2023-11-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_auto_20231101_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrysociety',
            old_name='net_migration_rate',
            new_name='migrants_every_1000',
        ),
        migrations.RenameField(
            model_name='countrysociety',
            old_name='population_0_14_rate',
            new_name='population_0_14_percentage',
        ),
        migrations.RenameField(
            model_name='countrysociety',
            old_name='population_15_64_rate',
            new_name='population_15_64_percentage',
        ),
        migrations.RenameField(
            model_name='countrysociety',
            old_name='population_65_more_rate',
            new_name='population_65_more_percentage',
        ),
    ]
