# Generated by Django 3.2.18 on 2023-04-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_alter_country_income_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='income_level',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
