# Generated by Django 3.2.18 on 2023-10-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_alter_country_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='official_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
