# Generated by Django 3.2.18 on 2023-11-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_auto_20231101_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrysociety',
            old_name='urban_population_rate',
            new_name='urban_population_percentage',
        ),
    ]
