# Generated by Django 3.2.18 on 2023-11-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_rename_urban_population_rate_countrysociety_urban_population_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrysociety',
            old_name='fertility_rate',
            new_name='births_per_woman',
        ),
    ]
