# Generated by Django 3.2.18 on 2023-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_alter_country_income_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.JSONField(default=[]),
        ),
    ]
