# Generated by Django 3.2.18 on 2023-10-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_alter_country_official_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.JSONField(null=True),
        ),
    ]
