# Generated by Django 3.2.18 on 2023-10-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0010_alter_country_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='languages',
        ),
    ]
