# Generated by Django 3.2.18 on 2023-05-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0011_alter_country_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='acronym',
            new_name='iso_code',
        ),
    ]
