# Generated by Django 3.2.18 on 2023-11-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0011_auto_20231102_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryeconomy',
            name='gdp_agriculture',
            field=models.DecimalField(decimal_places=2, help_text='percentage of total GDP', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='gdp_industry',
            field=models.DecimalField(decimal_places=2, help_text='percentage of total GDP', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='gdp_services',
            field=models.DecimalField(decimal_places=2, help_text='percentage of total GDP', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='industrial_production_growth_rate',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='inflation_rate',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='labor_force_agriculture',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='labor_force_industry',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='labor_force_services',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='population_below_poverty_line',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='public_debt',
            field=models.DecimalField(decimal_places=2, help_text='percentage of GDP', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='real_gdp_growth_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='taxes',
            field=models.DecimalField(decimal_places=2, help_text='percentage of GDP', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='unemployment_rate',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countryeconomy',
            name='unemployment_rate_youth',
            field=models.DecimalField(decimal_places=2, help_text='percentage of unemployment 15-24', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='alcohol_consumption_per_capita',
            field=models.DecimalField(decimal_places=2, help_text='liters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='beer_consumption_per_capita',
            field=models.DecimalField(decimal_places=2, help_text='liters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='births_every_1000',
            field=models.DecimalField(decimal_places=2, help_text='births every 1000 population', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='births_per_woman',
            field=models.DecimalField(decimal_places=2, help_text='children born/woman', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='deaths_every_1000',
            field=models.DecimalField(decimal_places=2, help_text='deaths every 1000 population', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='health_expenditure',
            field=models.DecimalField(decimal_places=2, help_text='as a percentage of GDP', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='hospital_bed_density',
            field=models.DecimalField(decimal_places=2, help_text='beds every 1000 population', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='life_expectancy_at_birth',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='life_expectancy_at_birth_female',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='life_expectancy_at_birth_male',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='literacy_rate',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='literacy_rate_female',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='literacy_rate_male',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='married_women_rate',
            field=models.DecimalField(decimal_places=2, help_text='ages 15-49', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='median_age',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='median_age_female',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='median_age_male',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='migrants_every_1000',
            field=models.DecimalField(decimal_places=2, help_text='migrants every 1000 population', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='obesity_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='physicians_density',
            field=models.DecimalField(decimal_places=2, help_text='physicians every 1000 population', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='population_0_14_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='population_15_64_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='population_65_more_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='population_females_65_more',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='population_growth_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='population_males_65_more',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='spirits_consumption_per_capita',
            field=models.DecimalField(decimal_places=2, help_text='liters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='tobacco_use',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='tobacco_use_female',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='tobacco_use_male',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='urban_population_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='countrysociety',
            name='wine_consumption_per_capita',
            field=models.DecimalField(decimal_places=2, help_text='liters', max_digits=10, null=True),
        ),
    ]
