# Generated by Django 3.2.18 on 2023-10-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0011_remove_country_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.JSONField(null=True),
        ),
    ]
