# Generated by Django 3.2.18 on 2023-11-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_auto_20231102_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='map',
        ),
        migrations.AddField(
            model_name='countrygeography',
            name='maps',
            field=models.URLField(null=True),
        ),
    ]
