# Generated by Django 3.2.18 on 2023-10-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_country_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryBorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3_country1', models.CharField(max_length=3)),
                ('iso3_country2', models.CharField(max_length=3)),
                ('length_km', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'country_border',
            },
        ),
        migrations.CreateModel(
            name='CountryGeography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=3)),
                ('coordinates', models.JSONField()),
                ('total_area_sq_km', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('land_area_sq_km', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('water_area_sq_km', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('area_ranking', models.IntegerField(null=True)),
                ('border_length_km', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('coastline_length_km', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('highest_point', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'country_geography',
            },
        ),
    ]
