# Generated by Django 3.2.18 on 2023-11-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_auto_20231103_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryCodes',
        ),
        migrations.AddField(
            model_name='country',
            name='gec',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso2',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
