# Generated by Django 3.2.18 on 2023-10-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_countryborder_countrygeography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrygeography',
            name='area_ranking',
        ),
    ]
