# Generated by Django 3.2.18 on 2023-09-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=255)),
                ('lng', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('admin_name', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('population', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
