# Generated by Django 3.2.18 on 2023-09-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
    ]
