# Generated by Django 3.2.18 on 2023-09-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_ascii',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
