# Generated by Django 3.2.18 on 2023-09-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_city_city_ascii'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='sm_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
